import '/styles/globals.css'
import { PT_Serif } from 'next/font/google'
import NavMenu from '@/components/NavMenu'


const pt_serif = PT_Serif({ subsets: ['latin'], weight:['400'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

      <html lang="en">
        <body className={pt_serif.className}>
          <NavMenu />
          {children}
        </body>
      </html>

  )
}
